name: Build and publish app

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  release-app-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - name: Write KeyStore 🗝️
        uses: ./.github/actions/prepare-keystore
        with:
          signingStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          signingKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          signingKeyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStoreBase64: ${{ secrets.KEYSTORE }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build APKs 📱
        run: ./gradlew assembleRelease

      - name: Upload APKs to Release 🚀
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: app/build/outputs/apk/release/*.apk

      - name: Upload APKs to Artifacts 📦
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*.apk

      - name: Build AABs 📱
        run: ./gradlew bundleRelease

      - name: Upload AABs to Release 🚀
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: app/build/outputs/bundle/release/*.aab

      - name: Upload AABs to Artifacts 📦
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: release-aabs
          path: app/build/outputs/bundle/release/*.aab
